### ISSUE TITLE
Redmine chat 

### ISSUE THREAD

**Issue by ashrafalzyoud** [MayamaTakeshi/redmine_rt#16]
Can u added this feature Redmine chat between members in project and show online or offline

**Comment by MayamaTakeshi** [comment]
There are so many chat solutions already available that it might not be worthy to do this.

Anyway there is already this plugin that provides chat:
  https://github.com/tigergm/redmine_layim
I would try to use that instead of working on a similar thing in redmine_rt.

I can see you are already asking its dev to support redmine 5:
  https://github.com/tigergm/redmine_layim/issues/3

So if I needed, I would update redmine_layim to support redmine 5.

**Comment by ashrafalzyoud** [comment]
@MayamaTakeshi 
Thx for your reply
And it's nice idea to update redmine layim

Thx for u

**Comment by ashrafalzyoud** [comment]
i hope listen nice news about update the redmine layim
@MayamaTakeshi

**Comment by MayamaTakeshi** [comment]
Hi, although upgrading from 4 to 5 would not be difficult (as I did it for redmine_rt) I can see there are open issues that were not answered:
  https://github.com/tigergm/redmine_layim/issues
So even if I were willing to do the upgrade from 4 to 5 we don't have a stable ground to work on it as first it would be necessary to be able to install redmine_layim in the original redmine 4 the author devoped for and solve any issues with it.
This would be more work than I could do. 
So I would search for something else.
